#!/usr/bin/env ansible-playbook
---
- name: Snapshot Rules
  hosts: localhost
  connection: local
  gather_facts: no

  vars_files:
      - vars/connection.yml
      - vars/credentials.yml

  vars:
    vg_name: "Ansible_VolumeGroup"
    vol_name: 'ansible_1'
    input: &connection_vars
      password: "{{ password }}"
      array_ip: "{{ array_ip_1 }}"
      user: "{{  user  }}"
      verifycert: false
    desired_retention: '24' #Time is in hours

  tasks:
    - name: Create new snapshot rule by interval
      dellemc_powerstore_snapshotrule:
        <<: *connection_vars
        name: "{{ 'Ansible_30_minute_rule' }}"
        days_of_week:
         - Monday
         - Wednesday
         - Friday
        desired_retention: "{{ desired_retention }}"
        interval: "Thirty_Minutes"
        state: "present"
    - name: Create a protection policy with snapshot rule
      dellemc_powerstore_protectionpolicy:
        <<: *connection_vars
        name: Ansible_policy1
        description: ansible_policy
        snapshotrules:
          - "Ansible_30_minute_rule"
        snapshotrule_state: "present-in-policy"
        state: "present"
    - name: Associate protection policy
      dellemc_powerstore_volumegroup:
        <<: *connection_vars
        vg_name: "{{vg_name}}"
        description: "This volume group is for ansible"
        state: "present"
        protection_policy: "Ansible_policy1"
